camunda:
  client:
    mode: saas
    auth:
      client-id: 80iA1_8DDNEd0LVwLf5hwOu7GPmFcM8Z
      client-secret: UFtlmvCfk21A_OO6C0VlZOyuMVElWvH-hVFgxnnJ4z95cXgfBIhQTMAUbEjy0kFk
    cluster-id: 83d96c80-028e-41e3-9005-8029fc1fc274
    region: bru-2
    zeebe:
      defaults:
        stream-enabled: false